export const DUMMY_JOBS = [
  {
    id: "mock-1",
    title: "Senior CNC Machine Operator",
    country: "Hungary",
    city: "Budapest",
    category: "Technical",
    salary_range: "€2,500 - €3,000",
    job_description: "We are seeking an experienced CNC Machine Operator to program, set up, and operate computer numerical control machines. You will be working in a state-of-the-art facility producing high-precision components for the automotive sector.",
    requirements: "- Minimum 3 years of CNC operation experience\n- Ability to read technical blueprints\n- Familiarity with Fanuc or Siemens controls",
    status: "active",
    created_at: new Date(Date.now() - 86400000 * 2).toISOString(),
    _count: { applications: 12 }
  },
  {
    id: "mock-2",
    title: "Assembly Line Worker",
    country: "Greece",
    city: "Athens",
    category: "Factory",
    salary_range: "€1,200 - €1,800",
    job_description: "Join our busy automotive parts manufacturing line. Your duties will involve assembling components, quality checking, and packaging. Full training provided. Accommodation and daily transport to the factory are included.",
    requirements: "- Physical stamina and manual dexterity\n- Attention to detail\n- Ability to work in shifts (including night shifts)\n- Valid passport",
    status: "active",
    created_at: new Date(Date.now() - 86400000 * 5).toISOString(),
    _count: { applications: 45 }
  },
  {
    id: "mock-3",
    title: "Commercial HVAC Technician",
    country: "Russia",
    city: "Moscow",
    category: "Technical",
    salary_range: "₽90,000 - 120,000",
    job_description: "Responsible for installing, maintaining, and repairing HVAC systems in large commercial buildings, including malls and hotels. Company provides shared accommodation and medical insurance.",
    requirements: "- Diploma or Certificate in HVAC\n- Minimum 2 years of commercial experience\n- Ability to work in varying climates\n- English or Russian communication skills",
    status: "active",
    created_at: new Date(Date.now() - 86400000 * 10).toISOString(),
    _count: { applications: 8 }
  },
  {
    id: "mock-4",
    title: "General Construction Laborer",
    country: "Belarus",
    city: "Minsk",
    category: "Construction",
    salary_range: "BYN 1,500 - 2,000",
    job_description: "General labor duties on large-scale commercial construction sites. Tasks include moving materials, assisting masons and carpenters, and site cleanup. Free housing, meals, and transport provided.",
    requirements: "- Good physical health and endurance\n- Willingness to do heavy lifting\n- Previous construction experience is an advantage but not required",
    status: "active",
    created_at: new Date(Date.now() - 86400000 * 15).toISOString(),
    _count: { applications: 120 }
  },
  {
    id: "mock-5",
    title: "Warehouse Inventory Manager",
    country: "Hungary",
    city: "Debrecen",
    category: "Warehouse",
    salary_range: "€2,000 - €2,500",
    job_description: "Manage daily warehouse operations, inventory tracking, logistics coordination, and team management for a major Eastern European distribution center.",
    requirements: "- Bachelor's degree in Logistics or Supply Chain\n- 5+ years of warehouse management experience\n- Proficiency in Warehouse Management Systems (WMS)\n- Fluent English",
    status: "active",
    created_at: new Date(Date.now() - 86400000 * 1).toISOString(),
    _count: { applications: 22 }
  },
  {
    id: "mock-6",
    title: "Food Processing Specialist",
    country: "Greece",
    city: "Thessaloniki",
    category: "Food Processing",
    salary_range: "€1,500 - €2,000",
    job_description: "Work in a modern food packaging and meat processing facility. Ensure strict hygiene and safety standards are met at all times.",
    requirements: "- Previous experience in food handling or processing\n- Understanding of HACCP and food safety regulations\n- Ability to work in cold temperature environments",
    status: "active",
    created_at: new Date(Date.now() - 86400000 * 7).toISOString(),
    _count: { applications: 56 }
  }
];
